Updated .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,46 +1,99 @@
 language: android
-jdk: oraclejdk8
-# Use the Travis Container-Based Infrastructure
-sudo: false
-
-cache:
-  directories:
-    - ${TRAVIS_BUILD_DIR}/gradle/caches/
-    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
-
+jdk:
+- oraclejdk8
 env:
   global:
-    - ANDROID_API_LEVEL=23
-    - EMULATOR_API_LEVEL=21
-    - ANDROID_BUILD_TOOLS_VERSION=23.0.2
-    - ANDROID_ABI=armeabi-v7a
-    - ANDROID_TAG=google_apis
-    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
-
+  - ANDROID_API=27
+  - EMULATOR_API=24
+  - ANDROID_BUILD_TOOLS=27.0.3
 android:
   components:
-    - tools # to get the new `repository-11.xml`
-    - platform-tools
-    - tools # to install Android SDK tools 25.1.x
-    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
-    - android-$ANDROID_API_LEVEL
-    - android-$EMULATOR_API_LEVEL
-    # For Google APIs
-    - addon-google_apis-google-$ANDROID_API_LEVEL
-    - addon-google_apis-google-$EMULATOR_API_LEVEL
-    # Google Play Services
-    - extra-google-google_play_services
-    # Support library
-    - extra-android-support
-    # Latest artifacts in local repository
-    - extra-google-m2repository
-    - extra-android-m2repository
-    # Specify at least one system image
-    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
-    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL
-
+  - tools
+  - android-$EMULATOR_API
+  - platform-tools
+  - tools
+  - build-tools-$ANDROID_BUILD_TOOLS
+  - android-$ANDROID_API
+  - extra-android-support
+  - extra-android-m2repository
+  - extra-google-m2repository
+  - sys-img-armeabi-v7a-android-$EMULATOR_API
+  licenses:
+  - ".+"
 before_script:
-  # Create and start emulator
-  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
-  - emulator -avd test -no-skin -no-audio -no-window &
-  - android-wait-for-emulator
+- echo "y" | android update sdk -a --no-ui --filter android-$EMULATOR_API
+- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$EMULATOR_API
+- android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # list all targets
+- echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
+- emulator -avd test -no-skin -no-window &
+- android-wait-for-emulator
+- adb shell input keyevent 82 &
+- adb wait-for-device get-serialno
+- cd ${TRAVIS_BUILD_DIR}
+- chmod +x gradlew
+- ./gradlew --version
+- ./gradlew clean
+script:
+- |
+  ./gradlew build assembleAndroidTest -PtestCoverageEnabled='true'
+  retval=$?
+  if [ $retval -ne 0 ]; then
+    echo "error on assembling, exit code: "$retval
+    exit $retval
+  fi
+# See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
+# Instead of this (which doesn't give any output during tests execution):
+# - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
+# run:
+- |
+  ./gradlew :app:installDebug :app:installDebugAndroidTest -PtestCoverageEnabled='true'
+  retval=$?
+  if [ $retval -ne 0 ]; then
+    echo "error on install, exit code: "$retval
+    exit $retval
+  fi
+#
+# The below line causes Process crash due to absence of video device
+#- adb shell am instrument -w -r -e debug false org.andstatus.app.tests/android.test.InstrumentationTestRunner
+#
+# Run only tests, marked with a special annotation:
+# See https://developer.android.com/reference/android/test/InstrumentationTestRunner.html
+# For testing one method only:
+# - adb shell am instrument -w -r -e debug false -e coverage true -e class org.andstatus.app.service.CommandExecutorStrategyTest#testSearch org.andstatus.app.tests/android.support.test.runner.AndroidJUnitRunner
+- |
+  adb shell am instrument -w -r -e executionMode travisTest -e coverage true org.andstatus.app.tests/android.support.test.runner.AndroidJUnitRunner |& tee build/adb-test.log
+  retval=$?
+  if [ $retval -ne 0 ]; then
+    echo "error in adb, exit code: "$retval
+    exit $retval
+  fi
+# adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
+# So we need to parse saved terminal log
+- |
+  cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack=" | grep -v "org.junit.AssumptionViolatedException"
+  if [ $? -eq 0 ]; then
+    echo "Test failure found"
+    exit 1
+  else
+    cat build/adb-test.log | grep "OK ("
+  fi
+# Copy coverage data from the emulator
+- |
+  adb shell "rm /sdcard/Download/coverage.ec"
+  adb shell "run-as org.andstatus.app cp /data/user/0/org.andstatus.app/files/coverage.ec /sdcard/Download"
+- cd app/build
+# copy to "build" folder, where it will be found by Sonar scanner
+- adb pull "/sdcard/Download/coverage.ec"
+- cd ../..
+notifications:
+  email: false
+cache:
+  directories:
+  - $HOME/.m2
+  - $HOME/.gradle/caches/
+  - $HOME/.gradle/wrapper/
+  - $HOME/.android/build-cache
+before_install:
+- yes | sdkmanager "platforms;android-27"
+after_success:
+  - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true
